/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmoJi: typeof import('./src/components/of/EmoJi.vue')['default']
    Frame: typeof import('./src/components/chat/Frame.vue')['default']
    FrameInput: typeof import('./src/components/chat/FrameInput.vue')['default']
    FrameInputRecord: typeof import('./src/components/chat/FrameInputRecord.vue')['default']
    FrameRightBtn: typeof import('./src/components/chat/FrameRightBtn.vue')['default']
    Loader: typeof import('./src/components/of/Loader.vue')['default']
    Main: typeof import('./src/components/chat/Main.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NhChat: typeof import('./src/components/chat/NhChat.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NullChat: typeof import('./src/components/svg/NullChat.vue')['default']
    NUpload: typeof import('naive-ui')['NUpload']
    RightButton: typeof import('./src/components/of/RightButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./src/components/of/Svg.vue')['default']
  }
}
